dist: trusty
language: node_js
cache: npm
sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
node_js:
  - "11"
branches:
  only:
  - master
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
install:
  - npm ci
script:
  - npm run test:smoke
after_failure:
  - cat /home/travis/.npm/_logs/*-debug.log