dist: trusty
language: node_js
cache: npm
sudo: required
services:
  - docker
node_js:
  - "11"
branches:
  only:
  - master
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
install:
  - npm ci
script:
  - npm run test:smoke
after_failure:
  - cat /home/travis/.npm/_logs/*-debug.log