dist: trusty
language: node_js
node_js:
  - "11"
branches:
  only:
  - master
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
install:
  - npm ci
script:
  - npm run test
after_failure:
  - cat *-debug.log