version: "3"

services:

  origin:
    image: parity/parity:v2.3.4
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ${DATA_DIR}/${ORIGIN}:/home/parity/.local/share/io.parity.ethereum/
    command: ["--chain", "${ORIGIN}", "--base-path", "/home/parity/.local/share/io.parity.ethereum/", "--jsonrpc-apis", "all", "--jsonrpc-interface", "all", "--jsonrpc-experimental"]

  auxiliary:
    image: ethereum/client-go
    ports:
      - "8546:8545"
      - "30304:30303"
    volumes:
      - ${DATA_DIR}/${AUXILIARY_NAME}:/chain_data
    command: ["--networkid", "${AUXILIARY_NETWORK}", "--datadir", "./chain_data", "--port", "30303", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcvhosts", "*", "--rpcapi", "eth,net,web3,personal", "--rpcport", "8545", "--ws", "--wsport", "8546", "--bootnodes", "${AUXILIARY_BOOTNODES}"]
